spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: your-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081

  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    root: INFO
    com.company.demo0: DEBUG

# Настройки для тестирования
test:
  containers:
    reuse: true

# Другие общие настройки приложения
app:
  name: demo0
